# 生成一个包含50条英文问答对的 input.txt 文件
qa_pairs = [
    ("What is the capital of France?", "Paris"),
    ("Who wrote the play Romeo and Juliet?", "William Shakespeare"),
    ("What is the largest planet in our solar system?", "Jupiter"),
    ("How many continents are there on Earth?", "Seven"),
    ("What is the chemical symbol for water?", "H2O"),
    ("What gas do plants absorb from the atmosphere?", "Carbon dioxide"),
    ("Who painted the Mona Lisa?", "Leonardo da Vinci"),
    ("What is the square root of 64?", "8"),
    ("Which element has the atomic number 1?", "Hydrogen"),
    ("How many legs does a spider have?", "Eight"),
    ("What is the capital of Japan?", "Tokyo"),
    ("Who discovered gravity?", "Isaac Newton"),
    ("What is the largest mammal?", "Blue whale"),
    ("How many days are there in a leap year?", "366"),
    ("Which planet is known as the Red Planet?", "Mars"),
    ("Who was the first president of the United States?", "George Washington"),
    ("What is the boiling point of water in Celsius?", "100"),
    ("What language is spoken in Brazil?", "Portuguese"),
    ("What is the capital of Canada?", "Ottawa"),
    ("Who invented the lightbulb?", "Thomas Edison"),
    ("What is the fastest land animal?", "Cheetah"),
    ("What is the capital of Germany?", "Berlin"),
    ("How many bones are in the adult human body?", "206"),
    ("What is the smallest prime number?", "2"),
    ("Which country is known for the Great Wall?", "China"),
    ("What organ pumps blood through the body?", "Heart"),
    ("Who was the famous female scientist who researched radioactivity?", "Marie Curie"),
    ("What is the freezing point of water in Celsius?", "0"),
    ("How many strings does a standard guitar have?", "Six"),
    ("What is the capital of Italy?", "Rome"),
    ("Which ocean is the largest?", "Pacific Ocean"),
    ("What is the name of our galaxy?", "Milky Way"),
    ("What do bees make?", "Honey"),
    ("Which animal is known as the King of the Jungle?", "Lion"),
    ("How many colors are there in a rainbow?", "Seven"),
    ("What is 10 multiplied by 10?", "100"),
    ("Who is the author of Harry Potter?", "J.K. Rowling"),
    ("What is the capital of Australia?", "Canberra"),
    ("What is the largest organ in the human body?", "Skin"),
    ("Who developed the theory of relativity?", "Albert Einstein"),
    ("What is the name of the fairy in Peter Pan?", "Tinker Bell"),
    ("Which bird is known for mimicking sounds?", "Parrot"),
    ("What is the capital of India?", "New Delhi"),
    ("How many planets are in the solar system?", "Eight"),
    ("What do cows drink?", "Water"),
    ("Which fruit is known to keep doctors away?", "Apple"),
    ("What is the capital of the United Kingdom?", "London"),
    ("What does a thermometer measure?", "Temperature"),
    ("What is the opposite of hot?", "Cold"),
    ("What is the tallest mountain in the world?", "Mount Everest"),
]

qa_text = "\n\n".join(f"Q: {q}\nA: {a}" for q, a in qa_pairs)

with open("D:\\model_project\\transformer!\\gpt\\input.txt", "w", encoding="utf-8") as f:
    f.write(qa_text)

"/mnt/data/minigpt_qa/input.txt"
